agent:
  image: swarm
  restart: always
  {% if discovery_tls_path -%}
  volumes:
    - {{ discovery_tls_path }}:/discovery_tls
  {%- endif %}
  command:
    - join
    - --advertise={{addr}}:{{port}}
    {% if discovery_tls_path -%}
    - --discovery-opt
    - kv.cacertfile=/discovery_tls/client-ca.pem
    - --discovery-opt
    - kv.certfile=/discovery_tls/client-cert.pem
    - --discovery-opt
    - kv.keyfile=/discovery_tls/client-key.pem
    {%- endif %}
    - {{connection_string}}/swarm
{%- if leader %}
manager:
  image: swarm
  restart: always
  ports:
    - 3376:2375
  volumes:
    - /etc/docker:/tls
    {% if discovery_tls_path -%}
    - {{ discovery_tls_path }}:/discovery_tls
    {%- endif %}
  command:
    - manage
    - --tlsverify
    - --tlscacert=/tls/ca.pem
    - --tlscert=/tls/server.pem
    - --tlskey=/tls/server-key.pem
    - --strategy
    - spread
    - --advertise
    - {{ addr }}:{{ port }}
    {% if discovery_tls_path -%}
    - --discovery-opt
    - kv.cacertfile=/discovery_tls/client-ca.pem
    - --discovery-opt
    - kv.certfile=/discovery_tls/client-cert.pem
    - --discovery-opt
    - kv.keyfile=/discovery_tls/client-key.pem
    {%- endif %}
    - {{ connection_string }}/swarm

{% endif -%}
